services:
- type: web
  name: telegram-shmulc-bot
  runtime: python
  plan: free
  branch: main
  buildCommand: pip install -r requirements.txt
  startCommand: python3 bot.py
  autoDeploy: false
  envVars:
  - key: BOT_TOKEN
    sync: false